<?php
/**
 * @author     DCKAP
 * @package    DCKAP_AdvancedSampleOrders
 * @copyright  Copyright (c) 2016 DCKAP Inc (http://www.dckap.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $buttonTitle = __('Add to Cart'); ?>
<?php $_product = $block->getProduct();?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart box-tosample">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty sample-qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary tocart" id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php if($block->isAllowSampleItem()) : ?>
            <input type="hidden" name="sample_product" class="sample_product" value="0">
            <input type="hidden" name="is_pdp" class="is_pdp" value="1" />
            <input type="hidden" name="label_value" class="label_value" value='<?php echo "( " . $block->getSamplePriceLabel() . " )";?>' />
            <button type="submit" title="Add Sample to Cart" class="action primary sample-addtocart" id="product-addsample-button" onclick="changeAction(this)">
                <span>Add Sample to Cart<label class="sample-label"><?php echo "( " . $block->getSamplePriceLabel() . " )"; ?></label></span>
            </button>
            <?php endif; ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if($block->isAllowSampleItem()) : ?>
    <script type="text/javascript">
        function changeAction(currentObject){
            var qty = document.getElementsByClassName("qty");
            for(var i = 0; i < qty.length; i++){
                if(parseInt(qty[i].value)){
                    qty[i].value = 1;
                }
            }
            jQuery('.sample_product').val(0);
            jQuery(currentObject).siblings('.sample_product').val(1);
            document.getElementById("product_addtocart_form").action = document.getElementById("product_addtocart_form").action+"stype/sample/";
        }
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>