<?php
/**
 * @author     DCKAP
 * @package    DCKAP_AdvancedSampleOrders
 * @copyright  Copyright (c) 2016 DCKAP Inc (http://www.dckap.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<strong class="product name product-item-name">
    <a href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getProductUrl()); ?>"><?= $block->escapeHtml($block->getProductName()) ?>
        <?php
        $quoteItem = $block->getItem()->getQuoteItem();
        if ($quoteItem && $quoteItem->getSampleType()) {
            $block->escapeHtml(__('( SAMPLE )'));
        } ?>
    </a></strong>
<?php if ($_options = $block->getOptionList()) : ?>
    <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])) : ?> class="tooltip wrapper"<?php endif; ?>>
                <?= /* @escapeNotVerified */ $block->escapeHtml($_formatedOptionValue['value']); ?>
                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                    <dl class="item options tooltip content">
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd><?= /* @escapeNotVerified */ $block->escapeHtml($_formatedOptionValue['full_view']); ?></dd>
                    </dl>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
<?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()) : ?>
    <?= $addtInfoBlock->setItem($block->getItem())->toHtml(); ?>
<?php endif; ?>
